apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: terraform-executor deployment configuration.
  labels:
    app: terraform-executor
  name: terraform-executor
spec:
  replicas: 0
  selector:
    matchLabels:
      app: terraform-executor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: terraform-executor
      name: terraform-executor
    spec:
      securityContext:
        runAsUser: 26
        fsGroup: 26
      initContainers: []
      containers: 
      - image: 'image-registry.openshift-image-registry.svc:5000/tower-terraform-demo/terraform-executor:latest'
        imagePullPolicy: Always
        name: terraform-executor
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        volumeMounts:
        - name: postgresql-volume
          mountPath: /var/lib/pgsql
        - name: terraform-scratch-volume
          mountPath: /home/terraform/terraform_scratch
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            cpu: "100m"
            memory: "512Mi"
      terminationGracePeriodSeconds: 75
      volumes:
      - name: postgresql-volume
        emptyDir: {}
      - name: terraform-scratch-volume
        emptyDir: {}
